### ISSUE TITLE
non-existent service "guzzle.client.steam" and "@guzzle.client.steam_user"

### ISSUE THREAD

**Issue by felixkpunkt** [SirWaddles/SteamAuthBundle#2]
Hey @SirWaddles ,
first of all, thanks for sharing your Bundle. I encountered a problem during the installation.

`The service "security.authentication.manager" has a dependency on a non-existent service "guzzle.client.steam".`

I looked in the services.yml file and there is no configuration for `@guzzle.client.steam` and `@guzzle.client.steam.user`

**Comment by kolvin** [comment]
Hey @qntm I also had this problem! have you done a composer install? initially i had an issue because i was running php 7 when the eightpoints/guzzle-bundle depends on having php 5.6  - so make sure your packages are all able to run with your PHP version and make sure all they are all installed! :)

**Comment by felixkpunkt** [comment]
I'm running Symfony 3.1.7 with PHP 5.6, I think that's not the problem. 
Did you do any other changes @TheClvn ?

**Comment by kolvin** [comment]
@qntm It wont be anything to do with your Symfony version :) - how are you using the bundle? have you kept as its its own bundle or are you using it within your AppBundle?

**Comment by felixkpunkt** [comment]
I installed it via composer and it's in the vendor folder. In my AppBundle I only have a route for rendering the Login-Template and a protected route.

**Comment by SirWaddles** [comment]
Hey,

Sorry, I left this part out of the documentation, forgot about it.
You just need to install Guzzle Bundle and initialise it in the AppKernel.

Those dependencies are created here
[SteamAuthExtension.php](https://github.com/SirWaddles/SteamAuthBundle/blob/master/DependencyInjection/SteamAuthExtension.php)

**Comment by felixkpunkt** [comment]
Hey,

I just found it by myself :) Maybe it's worth adding it to the documentation?
