### ISSUE TITLE
Symfony 3.2

### ISSUE THREAD

**Issue by sMunkK** [SirWaddles/SteamAuthBundle#4]
Hi sir! 
Do you think the bundle will be compatible with symfony 3.2?
And if yes, can u give me a date?
Ty in advance 
and gg for ur work

**Comment by SirWaddles** [comment]
I built it for 3.0, is there anything specific that doesn't work?

**Comment by sMunkK** [comment]
i don't know, actually if i clone the project, i can't composer update

**Comment by SirWaddles** [comment]
I updated the [Symfony Version Requirements](https://github.com/SirWaddles/SteamAuthBundle/commit/1be0d3f3ee5a9fe8a2e70ffa46a630ff70d742e8), try now.

**Comment by sMunkK** [comment]
Nice! Ty you sir :D Now i will try to do my best for try this :D I'm beginer in the codeFamily xD
Ty u again ;)

**Comment by sMunkK** [comment]
do you know that error ? "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "login_check" as such route does not exist.") in SteamAuthBundle:Login:login.html.twig at line 6."

**Comment by SirWaddles** [comment]
Yea, just add
```yml
login_check:
    path: /login_check
```
to your `app/routing.yml`

**Comment by sMunkK** [comment]
Nice one! But... return cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by SirWaddles** [comment]
That sounds like a server configuration issue. Try installing the `ca-certificates` package if you're on Ubuntu.

See the [Guzzle Verify](http://docs.guzzlephp.org/en/latest/request-options.html#verify-option) documentation for more info.

**Comment by sMunkK** [comment]
i'm on WAMP right now, i'm searching a solution on web ;)

**Comment by SirWaddles** [comment]
You can specify the location of the CA bundle using the [openssl.cafile](http://php.net/manual/en/openssl.configuration.php) option in php.ini

You can download [Mozilla's CA bundle](https://curl.haxx.se/ca/cacert.pem) from [curl's website](https://curl.haxx.se/docs/caextract.html).
